Adding new points to chapters in SCSVS
ComposableSecurity/SCSVS pull request #10
Opened 2023-01-21 09:14 UTC by deliriusz

2023-01-22 23:21 UTC, damianrusinek reviewed
Thanks for contributing! 
I've left some comments.

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x100-General/0x106-G6-Communications.md
> +| **G6.9** | Verify that contract does not enforce usage of "phantom functions" |
Please follow formatting (period at the end).

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x100-General/0x108-G8-Denial-of-Service.md
> +| **G8.13** | Don't rely on the contract 0 balance, as it can be forced to receive Ether via coinbase or selfdestruct. |
This is already in Business Logic category. Why do you suggest to copy it here?

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x100-General/0x109-G9-Blockchain-Data.md
> +| **G9.6** | Don't rely on block timestamp for precise operations, as they can be manipulated by miner. |
I am not aware of any real risk associated to 15 seconds spread of block timestamp. Could you elaborate?

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x200-Components/0x201-C1-Token.md
> +| **C1.10** | Make sure that the token does not have double entry point and does not track user balances in more than one smart contract. |
I would suggest to change it to form similar to: Verify that the protocol handles double-entry tokens (tracking user balances in a contract represented by two addresses) correctly or forbids them.

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x200-Components/0x203-C3-Oracle.md
> +| **C3.6** | Verify that the oracle implements Time Weighted Average Price (TWAP) funcitonality. |
TWAP is one type of oracles (price oracles) and this category considers building an oracle, not integrating with it.
I would suggest a check in Oracle Integration category that would propose to consider using TWAP for price on-chain oracles.

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x200-Components/0x203-C3-Oracle.md
> +| **C3.7** | Verify that the oracle price for an asset cannot be influenced accross single block. |
Verify that the price for an asset returned by oracle cannot be influenced in a single block.

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x200-Components/0x204-C4-Vault.md
> +| **C4.10** | If the vault is supposed to support fee-on-transfer tokens, make sure to check for balance change rather than amount to be transferred. |
Verify that the transferred amount is confirmed by checking balances before and after the deposit if the vault is going to support fee-on-transfer tokens (or any token is allowed).

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x200-Components/0x204-C4-Vault.md
> +| **C4.11** | Verify that the vault is only allowed to transfer tokens from msg.sender, to prohibit stealing from other users who set the allowance for the contract |
Verify that the vault is allowed to transfer tokens only from _msg.sender_ to prohibit stealing from users who approved the vault contract.

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x200-Components/0x204-C4-Vault.md
> +| **C4.11** | Verify that the deposit and withdraw business logic is consistent and simmetrical, especially when re-sending tokens to the same address (from == to). |
symmetrical

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x200-Components/0x205-C5-Bridge.md
> +| **C5.9** | Verify that priviledged contracts are separated from cross-chain relay calls. |
Could you elaborate what you mean here?

2023-01-22 23:21 UTC, damianrusinek commented on 2.0/0x300-Integrations/0x303-I3-Oracle.md
> +| **I4.5** | Whenever possible, use decentralized offchain oracles unsucceptible to price manipulatino attacks (e.g. Chainlink), ideally adding a fallback onchain oracle. |
typos
I am not sure that off-chain oracles is a good solution "whenever possible". They also have multiple downsides. And those are not always decentralized :)

2023-01-29 12:10 UTC, deliriusz commented on 2.0/0x200-Components/0x205-C5-Bridge.md
> +| **C5.9** | Verify that priviledged contracts are separated from cross-chain relay calls. |
Sure, this was the exact attack on Poly Network - https://research.kudelskisecurity.com/2021/08/12/the-poly-network-hack-explained/ . The attacker managed to escalate privileges via a function name hash collision on a relayed message. The attack was possible because relaying contract contained privileged function registering keepers, which could funnel the user funds out the of protocol.

2023-01-29 12:13 UTC, deliriusz commented on 2.0/0x300-Integrations/0x303-I3-Oracle.md
> +| **I4.5** | Whenever possible, use decentralized offchain oracles unsucceptible to price manipulatino attacks (e.g. Chainlink), ideally adding a fallback onchain oracle. |
Ok, I changed to "Consider using a decentralized offchain oracles unsucceptible to price manipulation attacks (e.g. Chainlink) for low liquidity asset, ideally adding a fallback onchain oracle." - what do you think?

2023-01-29 12:37 UTC, deliriusz commented on 2.0/0x100-General/0x109-G9-Blockchain-Data.md
> +| **G9.6** | Don't rely on block timestamp for precise operations, as they can be manipulated by miner. |
For example, using block.timestamp as a source of randomness (it happens to this day)

2023-02-03 11:04 UTC, damianrusinek requested changes
We have addressed all your questions and suggestions and added some small fixes and suggestions. 
Hopefully, it's the last review round :)

2023-02-03 11:04 UTC, damianrusinek commented on 2.0/0x300-Integrations/0x303-I3-Oracle.md
> +| **I4.5** | Consider using a decentralized off-chain oracles unsusceptible to price manipulation attacks (e.g. Chainlink) for low liquidity asset, ideally adding a fallback on-chain oracle. |
```suggestion
| **I4.5** | Verify that, the use a decentralized off-chain oracles unsusceptible to on-chain price manipulation attacks (e.g. Chainlink) is considered for low liquidity asset, ideally combining it with on-chain oracles to detect malicious values. |
```

2023-02-03 11:05 UTC, damianrusinek commented on 2.0/0x300-Integrations/0x303-I3-Oracle.md
> +| **I4.5** | Whenever possible, use decentralized offchain oracles unsucceptible to price manipulatino attacks (e.g. Chainlink), ideally adding a fallback onchain oracle. |
We have addressed it and proposed a final check :)

2023-02-07 05:59 UTC, deliriusz commented on 2.0/0x300-Integrations/0x303-I3-Oracle.md
> +| **I4.5** | Whenever possible, use decentralized offchain oracles unsucceptible to price manipulatino attacks (e.g. Chainlink), ideally adding a fallback onchain oracle. |
Done in https://github.com/ComposableSecurity/SCSVS/pull/10/commits/6dc31b45da4c9b07243c21f7d7dadb8b1a92bd61

2023-02-07 14:09 UTC, damianrusinek approved these changes

2023-02-07 14:10 UTC, merged