Added category I4: Bridge
ComposableSecurity/SCSVS pull request #12
Opened 2023-09-12 09:37 UTC by damianrusinek

2023-09-14 13:29 UTC, damianrusinek commented on README.md
> +    * [I4: Bridge](<./2.0/0x300-Integrations/0x304-I4-Bridge.md>)
```suggestion
    * [I4: Cross-Chain](<./2.0/0x300-Integrations/0x304-I4-Cross-Chain.md>)
```

2023-09-19 11:20 UTC, wh01s7 requested changes

2023-09-19 11:20 UTC, wh01s7 commented on 2.0/0x300-Integrations/0x304-I4-Cross-Chain.md
> +| **I4.LZ.6** | Verify that the UA's owner (ideally multisig) is able to call `forceResumeReceive` on the LZ endpoint to unblock the cross-chain channel and protect from DoS. |
```suggestion
| **I4.LZ.6** | Verify that the UA's owner (ideally multi-sig) is able to call `forceResumeReceive` on the LZ endpoint to unblock the cross-chain channel and protect from DoS. |
```

2023-09-19 11:20 UTC, wh01s7 commented on 2.0/0x300-Integrations/0x304-I4-Cross-Chain.md
> +| **I4.LZ.7** | Verify that the LayerZero cross-chain call parameters are not hardcoded and can be passed in the function call. That includes: zroPaymentAddress, adapterParams, refundAddress, useZro.
```suggestion
| **I4.LZ.7** | Verify that the LayerZero cross-chain call parameters are not hardcoded and can be passed in the function call. That includes: `zroPaymentAddress`, `adapterParams`, `refundAddress`, `useZro`. |
```

2023-09-19 11:20 UTC, wh01s7 commented on 2.0/0x300-Integrations/0x304-I4-Cross-Chain.md
> +| **I4.LZ.10** | Verify that the protocol uses production-ready examples of code prepared by LayerZero team for specific usages (e.g. OFT, ONFT, LzApp, NonBlockingLzApp). |
```suggestion
| **I4.LZ.10** | Verify that the protocol uses production-ready examples of code prepared by LayerZero team for specific usages (e.g. `OFT`, `ONFT`, `LzApp`, `NonBlockingLzApp`). |
```

2023-09-19 11:52 UTC, wh01s7 approved these changes

2023-09-19 11:55 UTC, ComposableSecurityTeam approved these changes

2023-09-19 11:55 UTC, merged

2025-03-28 02:01 UTC, Balmasexy approved these changes