Patch 1 - Preparing SCSVS v2 for release
ComposableSecurity/SCSVS pull request #7
Opened 2022-12-29 06:26 UTC by wh01s7

I added some checks, improved the English, added one new category - Vaults and removed the remaining empty categories.

2022-12-29 09:57 UTC, damianrusinek commented on 2.0/0x100-General/0x107-G7-Arithmetic.md
> +| **G7.9** | Verify that rounding with extreme conditions does not result in larger than expected losses. |
Losses larger than expected? What losses?

2022-12-29 10:01 UTC, damianrusinek commented on 2.0/0x200-Components/0x204-C4-Vault.md
> +| **C4.2** | Verify that the user's balance is updated based on funds received and not funds sent. |
"Verify that the user's balance is updated based on funds received and not funds **declared to be** sent."

2022-12-30 02:20 UTC, wh01s7 commented on 2.0/0x100-General/0x107-G7-Arithmetic.md
> +| **G7.9** | Verify that rounding with extreme conditions does not result in larger than expected losses. |
Bug example:
https://github.com/OpenCoreCH/smart-contract-audits/blob/main/reports/c4/rigor.md#high-significant-rounding-errors-for-interest-calculation

Maybe it will be better to rephrase it to "Verify that rounding in extreme conditions (different scale) or multiple function calls do not cause amplified losses." to be more precise.

2023-01-06 09:18 UTC, damianrusinek commented on 2.0/0x200-Components/0x205-C5-Bridge.md
> +| **C5.4** | Verify that bridge includes source and destination chain identifiers in the signed message and correctly verifies them. |
`chains` should remain
"source and destination chains"

2023-01-06 21:19 UTC, damianrusinek commented on 2.0/0x100-General/0x107-G7-Arithmetic.md
> +| **G7.9** | Verify that rounding with extreme conditions does not result in larger than expected losses. |
I would suggest two:
Verify that rounding uses secure granularity (e.g. seconds instead of days).
Verify that rounding in extreme conditions (e.g. very often) does not cause amplified losses (e.g. lack of interests accured).

I would also suggest to add that link to references.

2023-01-06 21:22 UTC, damianrusinek commented on 2.0/0x200-Components/0x204-C4-Vault.md
> +| **C4.1** | Verify that there are no vulnerabilities associated with the Vault component. |
Do we still need this type of unclear checks?

2023-01-06 21:25 UTC, damianrusinek commented on 2.0/0x200-Components/0x205-C5-Bridge.md
> +| **C5.7** | Verify signed message cannot be used in a different context (use domain separator from EIP-712). |
`| **C5.7** | Verify that signed message cannot be used in a different context (use domain separator from EIP-712). |`

`| **C5.8** | Verify that the case of 0 being returned by ecrecover function is handled securely. |`

2023-01-06 21:27 UTC, damianrusinek commented on 2.0/0x300-Integrations/0x303-I3-Oracle.md
> +| **I3.3** |  Verify that Oracle data is up-to-date. |
| **I3.3** |  Verify that data returned by Oracle is up-to-date. |

2023-01-06 21:28 UTC, damianrusinek commented on 2.0/0x300-Integrations/0x303-I3-Oracle.md
> +| **I3.3** |  Verify that Oracle data is up-to-date. |
`| **I3.4** |  Verify that no spot oracle is used (e.g. spot price from Uniswap pool). |`

2023-01-06 21:31 UTC, damianrusinek requested changes
I left a few comments and proposed a few checks.

2023-01-07 14:41 UTC, wh01s7 commented on 2.0/0x100-General/0x107-G7-Arithmetic.md
> +| **G7.9** | Verify that rounding with extreme conditions does not result in larger than expected losses. |
Sounds good to me.

PS. I think it should be *accrued

2023-01-07 14:47 UTC, wh01s7 commented on 2.0/0x200-Components/0x205-C5-Bridge.md
> +| **C5.4** | Verify that bridge includes source and destination chain identifiers in the signed message and correctly verifies them. |
I don't think so. It should be "chain" - those are chain identifiers.

2023-01-07 14:51 UTC, wh01s7 commented on 2.0/0x200-Components/0x204-C4-Vault.md
> +| **C4.1** | Verify that there are no vulnerabilities associated with the Vault component. |
Many people have reported that this kind of checks are not clear to them. In my opinion, this check makes sense because it allows you to add new types of vulnerabilities that SCSVS does not yet cover, and you are just completing it.

I would say that it is more important to explain how to use it in practice.

However, if there are still votes to throw it out - we will.

2023-01-12 15:10 UTC, ComposableSecurityTeam commented on 2.0/0x200-Components/0x204-C4-Vault.md
> +| **C4.1** | Verify that there are no vulnerabilities associated with the Vault component. |
Leaving it for now.

2023-01-12 15:21 UTC, merged